# .LOC[]

In [2]:
import numpy as np
import pandas as pd
df = pd.read_csv("datasets/players_20.csv")
df.set_index("short_name", inplace = True)

In [3]:
df = df[[ "long_name","age","dob","height_cm","weight_kg","nationality","club"] ]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [4]:
# # df.loc["L. Messi","weight_kg"]
# df.loc[:,"weight_kg"]
# df.loc["L. Messi","age":"nationality"]

In [5]:
col = ["long_name","age","dob","height_cm","weight_kg","nationality"]
df.loc[(df["height_cm"]>180) &( df["nationality"] == "Portugal"),col]

,long_name,age,dob,height_cm,weight_kg,nationality
short_name,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal
A. Lopes,Anthony Lopes,28,1990-10-01,184,81,Portugal
João Cancelo,João Pedro Cavaco Cancelo,25,1994-05-27,182,74,Portugal
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal
William Carvalho,William Silva de Carvalho,27,1992-04-07,187,83,Portugal
...,...,...,...,...,...,...
João Pereira,João Duarte Vieira Pereira,29,1990-05-10,183,79,Portugal
Rúben Fonseca,Rúben Miguel Valente Fonseca,19,2000-02-24,188,82,Portugal
Filipe Ferreira,Filipe Ferreira Marques,21,1998-02-25,186,73,Portugal
Wilson Carvalho,Wilson Roberto Bento De Carvalho,25,1993-07-04,183,77,Portugal
Alexandre Pimenta,A. Pimenta Flora Pimenta,20,1999-03-02,184,75,Portugal

# .iloc[]

In [9]:
# df.iloc[0,:]

In [10]:
# df.iloc[:,1]

# Drop Sample

In [25]:
df.drop("L. Messi",axis = 0)
# df.sample(random_state = 99,frac = 2,replace = True)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# Querry

In [7]:
import numpy as np
import pandas as pd
df = pd.read_csv("datasets/players_20.csv")
df.set_index("short_name", inplace = True)
df.query("age>34")
df[df["age"]>34]

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
Z. Ibrahimović,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy,85,...,53+4,57+4,57+4,57+4,53+4,50+4,52+4,52+4,52+4,50+4
Pepe,120533,https://sofifa.com/player/120533/kepler-lavera...,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto,84,...,73+3,76+3,76+3,76+3,73+3,75+3,82+3,82+3,82+3,75+3
G. Buffon,1179,https://sofifa.com/player/1179/gianluigi-buffo...,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Casillas,5479,https://sofifa.com/player/5479/iker-casillas-f...,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
F. Quagliarella,159261,https://sofifa.com/player/159261/fabio-quaglia...,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria,83,...,54+2,54+2,54+2,54+2,54+2,50+2,45+2,45+2,45+2,50+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N. Hunt,138083,https://sofifa.com/player/138083/nicky-hunt/20...,Nicky Hunt,35,1983-09-03,185,86,England,Crewe Alexandra,55,...,54+2,55+2,55+2,55+2,54+2,53+2,58+2,58+2,58+2,53+2
K. Ogi,232539,https://sofifa.com/player/232539/kota-ogi/20/1...,荻 晃太,36,1983-05-05,185,76,Japan,Vissel Kobe,55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
J. McCombe,11430,https://sofifa.com/player/11430/jamie-mccombe/...,Jamie McCombe,36,1983-01-01,196,79,England,Lincoln City,52,...,38+2,44+2,44+2,44+2,38+2,41+2,50+2,50+2,50+2,41+2
G. Maley,245558,https://sofifa.com/player/245558/gary-maley/20...,Gary Maley,36,1982-08-03,188,90,Scotland,Livingston FC,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zhou Ting,182461,https://sofifa.com/player/182461/ting-zhou/20/...,周挺,40,1979-02-05,182,73,China PR,Dalian YiFang FC,49,...,48+2,50+2,50+2,50+2,48+2,48+2,51+2,51+2,51+2,48+2