# .LOC[]

In [30]:
import numpy as np
import pandas as pd
df = pd.read_csv("datasets/players_20.csv")
df.set_index("short_name", inplace = True)

In [31]:
df = df[[ "long_name","age","dob","height_cm","weight_kg","nationality","club"] ]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [32]:
# # df.loc["L. Messi","weight_kg"]
# df.loc[:,"weight_kg"]
# df.loc["L. Messi","age":"nationality"]

In [33]:
col = ["long_name","age","dob","height_cm","weight_kg","nationality"]
df.loc[(df["height_cm"]>180) &( df["nationality"] == "Portugal"),col]

,long_name,age,dob,height_cm,weight_kg,nationality
short_name,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal
A. Lopes,Anthony Lopes,28,1990-10-01,184,81,Portugal
João Cancelo,João Pedro Cavaco Cancelo,25,1994-05-27,182,74,Portugal
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal
William Carvalho,William Silva de Carvalho,27,1992-04-07,187,83,Portugal
...,...,...,...,...,...,...
João Pereira,João Duarte Vieira Pereira,29,1990-05-10,183,79,Portugal
Rúben Fonseca,Rúben Miguel Valente Fonseca,19,2000-02-24,188,82,Portugal
Filipe Ferreira,Filipe Ferreira Marques,21,1998-02-25,186,73,Portugal
Wilson Carvalho,Wilson Roberto Bento De Carvalho,25,1993-07-04,183,77,Portugal
Alexandre Pimenta,A. Pimenta Flora Pimenta,20,1999-03-02,184,75,Portugal

# .iloc[]

In [34]:
# df.iloc[0,:]

In [35]:
# df.iloc[:,1]

# Drop Sample

In [36]:
df.drop("L. Messi",axis = 0)
# df.sample(random_state = 99,frac = 2,replace = True)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# Querry

In [37]:
import numpy as np
import pandas as pd
df = pd.read_csv("datasets/players_20.csv")
df.set_index("short_name", inplace = True)
df = df[[ "long_name","age","dob","height_cm","weight_kg","nationality","club"] ]
# df.query("age>34")
# df[df["age"]>34]

In [38]:
# df.query("age>34 and nationality=='Italy'")
# df.query("not (age>34)")
df["dob"] = df["dob"].astype("datetime64[ns]")

In [39]:
df["dob"].dt.year

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int32

# .apply()

In [40]:
df.query("dob.dt.year > 1990")
df["age"].apply(np.sqrt)

short_name
L. Messi             5.656854
Cristiano Ronaldo    5.830952
Neymar Jr            5.196152
J. Oblak             5.099020
E. Hazard            5.291503
                       ...
Shao Shuai           4.690416
Xiao Mingjie         4.690416
Zhang Wei            4.358899
Wang Haijian         4.242641
Pan Ximing           5.099020
Name: age, Length: 18278, dtype: float64

In [42]:
def clac_bmi(row):
    return row["weight_kg"]/(row["height_cm"]/100)**2
    
df.apply(clac_bmi,axis = 1)

short_name
L. Messi             24.913495
Cristiano Ronaldo    23.735308
Neymar Jr            22.204082
J. Oblak             24.615211
E. Hazard            24.163265
                       ...
Shao Shuai           22.835010
Xiao Mingjie         21.066743
Zhang Wei            21.678807
Wang Haijian         21.621622
Pan Ximing           23.547881
Length: 18278, dtype: float64

# Lambda Function

In [43]:
foo_lambda = lambda a,b: a+b
foo_lambda(3,2)

5

In [45]:
df_deep = df.copy(deep= True)
df_shawllow = df