In [39]:
import pandas as pd
# import numpy as np

In [40]:
df_cars = pd.read_csv("datasets/Car_sales.csv")
df_cars.head()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639

In [41]:
df_cars = df_cars[["Manufacturer","Sales_in_thousands",
                   "Vehicle_type","Price_in_thousands",
                   "Engine_size","Horsepower","Fuel_capacity"]]
df_cars.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

# agg

In [42]:
df_cars.agg("sum")

Manufacturer          AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...
Sales_in_thousands                                             8320.698
Vehicle_type          PassengerPassengerPassengerPassengerPassengerP...
Price_in_thousands                                             4245.567
Engine_size                                                       477.5
Horsepower                                                      29008.0
Fuel_capacity                                                    2800.5
dtype: object

In [43]:
df_cars.agg({"Sales_in_thousands":["sum","mean","max"],"Price_in_thousands":["sum","max","min"]})

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max           540.561000              85.500
min                  NaN               9.235

# Split apply Combine

In [44]:
passenger_filter = df_cars["Vehicle_type"]=="Passenger"
car_filter = df_cars["Vehicle_type"] == "Car"

In [45]:
avg_passenger= df_cars[passenger_filter]["Sales_in_thousands"].mean()
avg_cars = df_cars[car_filter]["Sales_in_thousands"].mean()

In [46]:
pd.DataFrame({"vehicle":["car","pass"],"sales_avg":[avg_passenger,avg_cars]})

  vehicle  sales_avg
0     car  43.234345
1    pass  80.622293

In [47]:
df_cars.groupby("Vehicle_type").mean(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,
Car,80.622293,26.319975,3.520000,186.400000,21.895000
Passenger,43.234345,27.763200,2.902586,185.793103,16.592241

In [48]:
df_cars_manu = df_cars.groupby("Manufacturer")
df_cars_manu.groups.keys()
df_cars_manu.get_group("BMW")

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
7,BMW,19.747,Passenger,26.99,2.5,170.0,16.6
8,BMW,9.231,Passenger,33.40,2.8,193.0,16.6
9,BMW,17.527,Passenger,38.90,2.8,193.0,18.5

In [49]:
df_cars.groupby("Manufacturer", as_index = False).mean(numeric_only=True)

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,19.751250,30.633333,2.925000,200.000000,16.400000
1,Audi,13.519000,39.980000,2.933333,220.000000,19.533333
2,BMW,15.501667,33.096667,2.700000,185.333333,17.233333
3,Buick,60.504750,26.781250,3.625000,206.250000,17.750000
4,Cadillac,22.435600,40.254000,4.500000,256.000000,20.800000
5,Chevrolet,61.596111,20.022778,3.055556,171.111111,15.477778
6,Chrysler,28.817286,23.430833,2.783333,194.833333,16.483333
7,Dodge,82.740818,24.213636,3.709091,199.545455,21.581818
8,Ford,183.875909,21.047273,3.327273,170.090909,19.063636
9,Honda,118.534800,20.277000,2.520000,160.400000,17.080000
10,Hyundai,45.775333,12.165667,1.966667,126.666667,14.533333
11,Infiniti,23.713000,29.465000,3.000000,227.000000,18.500000
12,Jaguar,15.467000,42.800000,3.000000,240.000000,18.400000
13,Jeep,97.717667,20.991667,3.500000,168.333333,19.833333
14,Lexus,17.807167,44.055000,3.616667,245.833333,20.533333
15,Lincoln,28.544667,41.690000,4.866667,263.333333,23.000000
16,Mercedes-B,13.013889,52.916667,3.422222,232.222222,18.922222
17,Mercury,39.666500,20.748333,3.150000,163.833333,17.833333
18,Mitsubishi,25.842143,22.167429,2.800000,165.142857,18.285714
19,Nissan,57.090714,22.360714,2.914286,169.000000,18.200000
20,Oldsmobile,29.831500,25.622833,3.450000,190.000000,18.200000
21,Plymouth,16.000250,22.642500,2.475000,166.750000,15.125000
22,Pontiac,61.755667,22.949167,3.433333,185.000000,17.916667
23,Porsche,4.042667,62.473333,3.166667,272.333333,17.000000
24,Saab,10.653000,29.610000,2.150000,177.500000,17.700000
25,Saturn,33.770000,14.271000,2.020000,119.600000,12.500000
26,Subaru,40.067500,21.395000,2.500000,165.000000,16.400000
27,Toyota,82.245000,21.982889,2.622222,160.666667,17.766667
28,Volkswagen,34.868667,17.698333,1.966667,120.833333,14.700000
29,Volvo,12.623333,30.933333,2.300000,182.166667,17.833333

In [56]:
df_cars.groupby("Vehicle_type").agg(min_sales = ("Sales_in_thousands","min"), max_sales = ("Sales_in_thousands","max"))

              min_sales  max_sales
Vehicle_type
Car               9.126    540.561
Passenger         0.110    247.994

In [78]:
df_cars.groupby("Manufacturer").sum(numeric_only=True).apply(lambda x : x * 1000)[["Price_in_thousands","Sales_in_thousands"]]

              Price_in_thousands  Sales_in_thousands
Manufacturer
Acura                    91900.0             79005.0
Audi                    119940.0             40557.0
BMW                      99290.0             46505.0
Buick                   107125.0            242019.0
Cadillac                201270.0            112178.0
Chevrolet               180205.0            554365.0
Chrysler                140585.0            201721.0
Dodge                   266350.0            910149.0
Ford                    231520.0           2022635.0
Honda                   101385.0            592674.0
Hyundai                  36497.0            137326.0
Infiniti                 29465.0             23713.0
Jaguar                   42800.0             15467.0
Jeep                     62975.0            293153.0
Lexus                   264330.0            106843.0
Lincoln                 125070.0             85634.0
Mercedes-B              476250.0            117125.0
Mercury                 124490.0            237999.0
Mitsubishi              155172.0            180895.0
Nissan                  156525.0            399635.0
Oldsmobile              153737.0            178989.0
Plymouth                 90570.0             64001.0
Pontiac                 137695.0            370534.0
Porsche                 187420.0             12128.0
Saab                     59220.0             21306.0
Saturn                   71355.0            168850.0
Subaru                   42790.0             80135.0
Toyota                  197846.0            740205.0
Volkswagen              106190.0            209212.0
Volvo                   185600.0             75740.0

In [82]:
num_cols = df_cars.select_dtypes(include= "number").columns
df_cars.groupby("Manufacturer")[num_cols].apply(lambda x : x - x.mean())[["Sales_in_thousands","Price_in_thousands"]]

                  Sales_in_thousands  Price_in_thousands
Manufacturer
Acura        0             -2.832250           -9.133333
             1             19.632750           -2.233333
             2             -5.637250                 NaN
             3            -11.163250           11.366667
Audi         4              6.878000          -15.990000
...                              ...                 ...
Volvo        152           -9.078333           -6.533333
             153            2.621667           -3.433333
             154            4.907667           -2.133333
             155           -9.130333           14.566667
             156            6.345667            5.066667

[157 rows x 2 columns]

In [92]:
def funct_filter(x) : 
    return x["Sales_in_thousands"].sum()>52
    
df_cars.groupby(["Manufacturer"]).filter(funct_filter)
# df_cars.groupby(["Manufacturer"]).filter(lambda x : x["Sales_in_thousands"].mean()>52 )

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.500,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.400,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.000,3.5,210.0,18.0
10,Buick,91.561,Passenger,21.975,3.1,175.0,17.5
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.400,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.500,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.800,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.500,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.000,2.9,201.0,21.1